language: node_js
node_js: 10

script:
  - yarn
  - yarn lint
  #- yarn test
  - yarn build

branches:
  only:
    - master
    - /^v\d+.\d+(.\d+)?(-\S*)?$/

deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh prod
    on:
      branch: master
      tags: true
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh staging
    on:
      branch: master
