language: node_js
node_js: null

script:
  - npm ci
  - npm run lint
  #- npm run test
  - npm run build

branches:
  only:
    - master
    - /^v\d+.\d+(.\d+)?(-\S*)?$/

deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh prod
    on:
      branch: master
      tags: true
